### ISSUE TITLE
Course completed event use the event userid instead of relateduserid as actor 

### ISSUE THREAD

**Issue by henrikvongunten** [LearningLocker/Moodle-xAPI-Translator#50] opened 2017-05-08 13:19 UTC
When using the Moodle xAPI plugins, the wrong actor seem to be sent in the course completion statements.

The admin user is recorded as the actor in the statement instead of the log event "related user". While viewing the statement in LL, it look like the admin user is completing the course multiple times.

LL Report for completed courses:

 Admin User completed Course 1 | 19 hours ago (Thu, May 4, 2017 10:51 AM)
 Admin User completed Course 1 | 19 hours ago (Thu, May 4, 2017 10:42 AM)

Log event for user 6:

"http://lrs.learninglocker.net/define/extensions/moodle_logstore_standard_log": {
                "eventname": "\\core\\event\\course_completed",
                "component": "core",
                "action": "completed",
                "objecttable": "course_completions",
                "objectid": "5",
                "crud": "u",
                "edulevel": 2,
                "contextid": 22,
                "contextlevel": 50,
                "contextinstanceid": "2",
                "userid": "2",
                "courseid": "2",
                "relateduserid": "6",
                "other": "a:1:{s:13:\"relateduserid\";s:1:\"6\";}",
                "timecreated": 1493894522,
                "origin": "cli",
                "object": "course"

Log event for user 7:

"http://lrs.learninglocker.net/define/extensions/moodle_logstore_standard_log": {
                "eventname": "\\core\\event\\course_completed",
                "component": "core",
                "action": "completed",
                "objecttable": "course_completions",
                "objectid": "6",
                "crud": "u",
                "edulevel": 2,
                "contextid": 22,
                "contextlevel": 50,
                "contextinstanceid": "2",
                "userid": "2",
                "courseid": "2",
                "relateduserid": "7",
                "other": "a:1:{s:13:\"relateduserid\";s:1:\"7\";}",
                "timecreated": 1493895062,
                "origin": "cli",
                "object": "course"

**Comment by bvukas** [comment] 2017-05-08 13:42
I've just created the same issue #49 :)

**Comment by ryansmith94** [comment] 2017-05-08 15:19
Duplicate of #49

**Closed by ryansmith94** 2017-05-08 15:19 UTC
